services:
  frontend:
    build:
      dockerfile: kafka-utils-fe/development.Dockerfile
    ports:
      - 4300:4200
    volumes:
      - ./kafka-utils-fe/src:/home/app/src
      - node_modules:/home/app/node_modules

  backend:
    build:
      dockerfile: kafka-utils-be/development.Dockerfile
    ports:
      - 8083:8083
    develop:
      watch:
        - path: ./kafka-utils-be/src
          action: rebuild

volumes:
  node_modules: